sources:
  - type: github
    url: https://github.com
    token: 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

sync-all-repo: false
source-repositories:
  - amd-rig
  - GBApp
default-pull-directory: tmp_work

targets:
  # - gitea:
  #   url: https://gitea.com
  #   token: aaa*
  - type: local
    dir: local
